<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-5OQL5T2" ignored="0" name="Login with negative scenario" tests="2" failures="1" timestamp="04 Aug 2022 11:33:43 GMT" time="14.474" errors="0">
  <testcase name="initbrowser" time="13.812" classname="Testcase_Swaglabs.Negativetestcase01"/>
  <testcase name="login" time="0.655" classname="Testcase_Swaglabs.Negativetestcase01">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 1, Size: 1">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at Testcase_Swaglabs.Negativetestcase01.login(Negativetestcase01.java:34)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- Login with negative scenario -->
